{{- if .Values.metrics.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "muffin-wallet-chart.fullname" . }}
  labels:
    {{- include "muffin-wallet-chart.labels" . | nindent 4 }}
    release: prometheus
spec:
  selector:
    matchLabels:
      {{- include "muffin-wallet-chart.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: http
      path: {{ .Values.metrics.serviceMonitor.path | default "/actuator/prometheus" }}
      interval: {{ .Values.metrics.serviceMonitor.interval | default "15s" }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
{{- end }}
